# Generated by Django 6.0.6 on 2026-08-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_linkedin_sync_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='authored_by',
            field=models.CharField(blank=True, choices=[('ai', 'AI'), ('human', 'Human')], default=None, help_text='Who/what composed this outgoing message. Null = incoming, or an outgoing message synced before this field existed.', max_length=10, null=True, verbose_name='Authored by'),
        ),
    ]
