import sys
from datetime import datetime, timezone
from pathlib import Path

from django.core.management import call_command
from django.core.management.base import BaseCommand
from django.db import connections

from linkedin.conf import ROOT_DIR

# Regenerated by `migrate` on the Postgres side — dumping them would just collide
# with (or shadow) the target DB's own rows. --natural-foreign still lets any FK
# pointing at them (e.g. chat.ChatMessage's GenericForeignKey content_type, or
# auth.User FKs) resolve correctly against Postgres's own copies.
EXCLUDED_APPS = ["contenttypes", "auth.permission", "sessions.session", "admin.logentry"]


class Command(BaseCommand):
    help = (
        "One-time upgrade helper: copy data from an existing data/db.sqlite3 file "
        "into the Postgres database configured in settings. Run once after "
        "upgrading an existing self-hosted install from SQLite to Postgres."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--sqlite-path",
            default=str(ROOT_DIR / "data" / "db.sqlite3"),
            help="Path to the legacy SQLite database file.",
        )

    def handle(self, *args, **options):
        sqlite_path = Path(options["sqlite_path"])
        if not sqlite_path.exists():
            self.stderr.write(f"No SQLite database found at {sqlite_path}.")
            sys.exit(1)

        connections.databases["sqlite_legacy"] = {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": str(sqlite_path),
        }

        self.stdout.write("Applying migrations to Postgres...")
        call_command("migrate", verbosity=0)

        export_path = (
            ROOT_DIR / "data" / f"sqlite_export_{datetime.now(timezone.utc):%Y%m%d%H%M%S}.json"
        )
        self.stdout.write(f"Exporting data from {sqlite_path}...")
        call_command(
            "dumpdata",
            natural_foreign=True,
            natural_primary=True,
            exclude=EXCLUDED_APPS,
            database="sqlite_legacy",
            output=str(export_path),
        )

        self.stdout.write("Loading data into Postgres...")
        call_command("loaddata", str(export_path), database="default")

        self.stdout.write(
            self.style.SUCCESS(f"Migration complete. Export kept at {export_path} as a backup.")
        )
