import os
import sys
from datetime import datetime, timezone
from pathlib import Path

from django.apps import apps
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.core.management import call_command
from django.core.management.base import BaseCommand, CommandError
from django.db import connections

from db_url import django_db_config, get_database_url
from linkedin.conf import ROOT_DIR

# contenttypes/permissions are regenerated by `migrate` on the target from the
# installed-app set, so dumping them would collide with (or shadow) the target's
# own rows. --natural-foreign still lets any FK pointing at them (chat's
# GenericForeignKey content_type, auth.User FKs) resolve against the target copies.
EXCLUDED_APPS = ["contenttypes", "auth.permission"]

_TARGET_ALIAS = "postgres_target"


class Command(BaseCommand):
    help = (
        "Copy all data from the current (local) Postgres into a remote Postgres "
        "such as Supabase / Neon / RDS. Source is the ambient DATABASE_URL; the "
        "target is given by --target-url (or the TARGET_DATABASE_URL env var). "
        "The target's schema is migrated first, then data is loaded and row counts "
        "are verified. The target should be empty (fresh project) — its own rows "
        "for tables being loaded would otherwise collide on primary key."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--target-url",
            default=os.environ.get("TARGET_DATABASE_URL"),
            help=(
                "DATABASE_URL of the remote Postgres to copy into, e.g. "
                "postgresql://postgres:pw@db.xxx.supabase.co:5432/postgres?sslmode=require"
            ),
        )

    def handle(self, *args, **options):
        target_url = options["target_url"]
        if not target_url:
            raise CommandError(
                "No target given. Pass --target-url or set TARGET_DATABASE_URL, e.g.\n"
                "  --target-url 'postgresql://postgres:pw@db.xxx.supabase.co:5432/postgres?sslmode=require'"
            )

        source_url = get_database_url()
        if _same_endpoint(source_url, target_url):
            raise CommandError("Target is the same database as the source — nothing to do.")

        manage_py = str(ROOT_DIR / "manage.py")
        export_path = (
            ROOT_DIR / "data" / f"postgres_export_{datetime.now(timezone.utc):%Y%m%d%H%M%S}.json"
        )
        export_path.parent.mkdir(parents=True, exist_ok=True)

        # Phases 2 & 3 run in a subprocess with the target as `default`
        # (via DATABASE_URL). migrate's historical data migrations and loaddata
        # both operate on `default` with no `.using(...)`, so the target has to be
        # the default there. The parent process keeps the source as default for
        # the dump (phase 1) and the source side of verification (phase 4).
        target_env = {**os.environ, "DATABASE_URL": target_url}
        # Drop the POSTGRES_* fallbacks so a stray one can't override DATABASE_URL
        # in the child (get_database_url prefers DATABASE_URL, but be explicit).
        for var in ("POSTGRES_DB", "POSTGRES_USER", "POSTGRES_PASSWORD", "POSTGRES_HOST", "POSTGRES_PORT"):
            target_env.pop(var, None)

        self.stdout.write(f"Source: {_redact(source_url)}")
        self.stdout.write(f"Target: {_redact(target_url)}")

        self.stdout.write("1/4 Exporting all data from the local Postgres...")
        call_command(
            "dumpdata",
            "--natural-foreign", "--natural-primary",
            *[arg for app in EXCLUDED_APPS for arg in ("--exclude", app)],
            "-o", str(export_path),
        )

        self.stdout.write("2/4 Applying migrations to the remote Postgres...")
        _run(manage_py, ["migrate", "--no-input", "-v", "0"], target_env)

        self.stdout.write("3/4 Loading data into the remote Postgres...")
        _run(manage_py, ["loaddata", str(export_path)], target_env)

        self._verify_row_counts(target_url)

        self.stdout.write(
            self.style.SUCCESS(f"Migration complete. Export kept at {export_path} as a backup.")
        )

    def _verify_row_counts(self, target_url: str) -> None:
        """Compare every migrated table's row count, source vs target.

        ContentType/Permission are skipped: they're regenerated per the
        installed-app set on the target, so their counts legitimately differ.
        """
        connections.databases[_TARGET_ALIAS] = django_db_config(target_url)

        self.stdout.write("\nRow-count verification (local -> remote):")
        regenerated = {ContentType, Permission}
        mismatches = 0
        for model in sorted(apps.get_models(include_auto_created=True), key=lambda m: m._meta.label):
            if model in regenerated:
                continue
            src = model.objects.using("default").count()
            dst = model.objects.using(_TARGET_ALIAS).count()
            flag = "" if src == dst else "  <-- MISMATCH"
            if src != dst:
                mismatches += 1
            self.stdout.write(f"  {model._meta.label:<32} {src:>8} -> {dst:>8}{flag}")

        if mismatches:
            self.stderr.write(
                self.style.ERROR(
                    f"{mismatches} table(s) did not match. Inspect the rows above — the JSON "
                    "export is kept as a backup so you can retry.",
                ),
            )
            sys.exit(1)
        self.stdout.write(self.style.SUCCESS("All data tables match — nothing left behind."))


def _run(manage_py: str, argv: list, env: dict) -> None:
    import subprocess

    subprocess.run([sys.executable, manage_py, *argv], cwd=ROOT_DIR, env=env, check=True)


def _same_endpoint(a: str, b: str) -> bool:
    from urllib.parse import urlparse

    pa, pb = urlparse(a), urlparse(b)
    return (pa.hostname, pa.port or 5432, pa.path) == (pb.hostname, pb.port or 5432, pb.path)


def _redact(url: str) -> str:
    from urllib.parse import urlparse, urlunparse

    parts = urlparse(url)
    if parts.password:
        netloc = parts.netloc.replace(f":{parts.password}@", ":****@")
        parts = parts._replace(netloc=netloc)
    return urlunparse(parts)
