import sys
from datetime import datetime, timezone
from pathlib import Path

from django.core.management import call_command
from django.core.management.base import BaseCommand
from django.db import connections

from linkedin.conf import ROOT_DIR

# Regenerated by `migrate` on the Postgres side — dumping them would just collide
# with (or shadow) the target DB's own rows. --natural-foreign still lets any FK
# pointing at them (e.g. chat.ChatMessage's GenericForeignKey content_type, or
# auth.User FKs) resolve correctly against Postgres's own copies.
# (The legacy SQLite's session/admin-log/site tables aren't listed here: those
# contrib apps are no longer installed, so dumpdata never exports them anyway —
# and naming an uninstalled app in --exclude raises "Unknown model".)
EXCLUDED_APPS = ["contenttypes", "auth.permission"]


class Command(BaseCommand):
    help = (
        "One-time upgrade helper: copy data from an existing data/db.sqlite3 file "
        "into the Postgres database configured in settings. Run once after "
        "upgrading an existing self-hosted install from SQLite to Postgres."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--sqlite-path",
            default=str(ROOT_DIR / "data" / "db.sqlite3"),
            help="Path to the legacy SQLite database file.",
        )

    def handle(self, *args, **options):
        sqlite_path = Path(options["sqlite_path"])
        if not sqlite_path.exists():
            self.stderr.write(f"No SQLite database found at {sqlite_path}.")
            sys.exit(1)

        # Aliases declared in settings.DATABASES get defaulted (TIME_ZONE, OPTIONS,
        # CONN_MAX_AGE, ...) by Django at startup. This one is added at runtime, so
        # it needs the full set spelled out or backend init raises a bare KeyError.
        connections.databases["sqlite_legacy"] = {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": str(sqlite_path),
            "USER": "",
            "PASSWORD": "",
            "HOST": "",
            "PORT": "",
            "OPTIONS": {},
            "TIME_ZONE": None,
            "CONN_MAX_AGE": 0,
            "CONN_HEALTH_CHECKS": False,
            "AUTOCOMMIT": True,
            "ATOMIC_REQUESTS": False,
            "TEST": {},
        }

        self.stdout.write("Applying migrations to Postgres...")
        call_command("migrate", verbosity=0)

        export_path = (
            ROOT_DIR / "data" / f"sqlite_export_{datetime.now(timezone.utc):%Y%m%d%H%M%S}.json"
        )
        self.stdout.write(f"Exporting data from {sqlite_path}...")
        call_command(
            "dumpdata",
            natural_foreign=True,
            natural_primary=True,
            exclude=EXCLUDED_APPS,
            database="sqlite_legacy",
            output=str(export_path),
        )

        self.stdout.write("Loading data into Postgres...")
        call_command("loaddata", str(export_path), database="default")

        self.stdout.write(
            self.style.SUCCESS(f"Migration complete. Export kept at {export_path} as a backup.")
        )
