# Generated by Django 6.0.5 on 2026-06-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='human_takeover',
            field=models.BooleanField(default=False, help_text='If True, AI will stop sending automated messages.', verbose_name='Human Takeover'),
        ),
    ]
