# Generated by Django 6.0.6 on 2026-08-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0012_collapse_llm_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchkeyword',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
