# Generated by Django 6.0.6 on 2026-08-27 13:41

"""Undo 0013, which was generated from model state that was never committed.

0013 added ``SearchKeyword.location`` as ``CharField(blank=True, default='')``.
Django applies such a default while backfilling and then **drops the DB-level
default**, leaving a NOT NULL column that every INSERT must supply a value for
— but no field was ever added to ``linkedin/models.py`` (nor to the
``webadmin/models.py`` SQLAlchemy mirror), and nothing anywhere reads or writes
it. So every ``SearchKeyword.objects.bulk_create`` in
``pipeline/search.py:run_search`` omitted the column and died on
NotNullViolation, failing the connect task on every cycle and stalling the
campaign outright.

Dropping the column loses nothing: it existed for a day, the AddField
backfilled all pre-existing rows with '', and no code path has ever written
anything else into it.
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0013_searchkeyword_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchkeyword',
            name='location',
        ),
    ]
