# Generated by Django 6.0.6 on 2026-08-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0014_remove_searchkeyword_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='search_locations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
