# Generated by Django 6.0.6 on 2026-08-28 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0015_campaign_search_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='search_locations',
            new_name='search_geo_urns',
        ),
    ]
