# Generated by Django 6.0.6 on 2026-08-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0016_rename_search_locations_campaign_search_geo_urns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('connect', 'Connect'), ('check_pending', 'Check Pending'), ('follow_up', 'Follow Up'), ('check_inbox', 'Check Inbox'), ('manual_send', 'Manual Send')], max_length=20),
        ),
    ]
